### ISSUE TITLE
can't finetune ssd_inception with this repository, what's the reason?

### ISSUE THREAD

**Issue by prashant0079** [bourdakos1/Custom-Object-Detection#16]
python object_detection/train.py --logtostderr --train_dir=train/ --pipeline_config_path=ssd_inception_v2_coco.config 
WARNING:tensorflow:From /home/prashant/Custom-Object-Detection/object_detection/trainer.py:176: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
Traceback (most recent call last):
  File "object_detection/train.py", line 198, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "object_detection/train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/prashant/Custom-Object-Detection/object_detection/trainer.py", line 192, in train
    clones = model_deploy.create_clones(deploy_config, model_fn, [input_queue])
  File "/home/prashant/Custom-Object-Detection/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/home/prashant/Custom-Object-Detection/object_detection/trainer.py", line 133, in _create_losses
    losses_dict = detection_model.loss(prediction_dict)
  File "/home/prashant/Custom-Object-Detection/object_detection/meta_architectures/ssd_meta_arch.py", line 431, in loss
    location_losses, cls_losses, prediction_dict, match_list)
  File "/home/prashant/Custom-Object-Detection/object_detection/meta_architectures/ssd_meta_arch.py", line 565, in _apply_hard_mining
    match_list=match_list)
  File "/home/prashant/Custom-Object-Detection/object_detection/core/losses.py", line 445, in __call__
    location_losses = tf.unstack(location_losses)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1054, in unstack
    (axis, -value_shape.ndims, value_shape.ndims))

**Comment by bourdakos1** [comment]
Hi @prashant0079, this repo relies on a dated version of the TensorFlow api. We've moved to a more future proof version here: https://github.com/cloud-annotations/training
I encourage you to try it out and reopen this issue there if you are still running into problems
