### ISSUE TITLE
when i run the last command   python object_detection/object_detection_runner.py

### ISSUE THREAD

**Issue by pigpeak** [bourdakos1/Custom-Object-Detection#8]
Traceback (most recent call last):
  File "object_detection/object_detection_runner.py", line 95, in <module>
    detect_objects(image_path)
  File "object_detection/object_detection_runner.py", line 64, in detect_objects
    plt.imshow(image_np, aspect = 'normal')
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 3080, in imshow
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1710, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 5189, in imshow
    self.set_aspect(aspect)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 1273, in set_aspect
    self._aspect = float(aspect)  # raise ValueError if necessary
ValueError: could not convert string to float: normal

**Comment by bourdakos1** [comment]
Check out issue #7
You can fix this by changing:
```python
plt.imshow(image_np, aspect = 'normal')
```

To
```python
plt.imshow(image_np)
```
Or
```python
plt.imshow(image_np, aspect = 'auto')
```
I will push an update to fix this soon :)

**Comment by bourdakos1** [comment]
finally pushed an update, sorry that took so long...
